name = "nextcord-gay"
type = "javascript"
zone_id = "647c59d2f26a89eb310ad728c5313876"
account_id = "57b702387c98c74ae1d6147aad215781"
route = "nextcord.gay/*"
workers_dev = true
compatibility_date = "2022-03-13"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
