name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env
        run: bash ../env.sh "$secrets"
        env:
          secrets: ${{ toJson(secrets) }}
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm test
